### ISSUE TITLE
Alternative table view for reference

### ISSUE THREAD

**Issue by ollehints** [geocollections/sarv-edit#123]
Some users feel unhappy with the default bootstrap styled table and wish to use more densely populated table for quick quality checking of many records etc. could we implement 'alternative table' in addition to table and list views? It would have fixed row height, and preferably user-changeable col widths. Filtering, sorting and paging should work as for regular table.

**Comment by ollehints** [comment]
ok, but it should be possible to limit the list of fields in the code, or by user (via multi-select combo). Currently the table is not well-formed due to null values that cause missing cells. Also, if possible, user would like to change column width by individual columns.

**Comment by enmust** [comment]
Tried multiple column resizing methods but none worked that well with our table implementation. Currently closing this because now it is possible to choose fields from multi-select combo which lets users remove unnecessary fields. 

Adding some methods of implementing resizeable columns for future use: 
- https://www.brainbell.com/javascript/making-resizable-table-js.html
- https://www.npmjs.com/package/vue-columns-resizable
- https://stackoverflow.com/questions/49370421/making-columns-resizable-in-bootstrap-4
