### ISSUE TITLE
API to log detail page requests

### ISSUE THREAD

**Issue by ollehints** [geocollections/sarv-edit#440]
Public API should log requests to detail views for tables to be specified in config. Especially important for doi, attachment, library tables. Need to make new table and config for that. Table should have fields for time, ip, table, row_id. Then detail pages can show counter and last visits.

**Comment by urtson** [comment]
API now logs the requests by pk from tables specified in log_tables list in config.
The query must be in the form https://rwapi.geocollections.info/doi/491, otherwise it is difficult to distinguish the single object query.
But edit currently sends the query as filtering by id: https://rwapi.geocollections.info/doi/?id=491
Could this be changed?

**Comment by ollehints** [comment]
we need to log public views (in rwapi we are interested to log changes rather than views).

**Comment by urtson** [comment]
Now writes into web_counter table
