### ISSUE TITLE
GPS location not updated

### ISSUE THREAD

**Issue by ollehints** [geocollections/sarv-edit#531]
In site view coordinates from GPS are often very coarse and get only updated if user opens another app that uses GPS. Same problem with android phone and ipad. This makes add site functionality inconvenient.
Can we query GPS more frequently or use another codebase?

**Comment by enmust** [comment]
Needs some testing because sometimes it seems to work and sometimes it initially takes coordinates from some kind of base station. After opening for example google maps then correct coordinates are taken.

**Comment by enmust** [comment]
Seems like this can't be fixed on our side. We are using the HTML Geolocation API which has some limitations and it is most accurate when the device has GPS. Most desktop/laptop computers do not have GPS sensors so the geolocation is received using network data. 

For example Google Maps also uses phone GPS to get exact location on desktop/laptop computers otherwise it just shows closest area to your location.

> Can we query GPS more frequently or use another codebase?
It immediately updates GPS location when it changes, we could try Google's geolocation API

**Comment by enmust** [comment]
https://developers.google.com/maps/documentation/geolocation/overview

**Comment by enmust** [comment]
Closed for now
