### ISSUE TITLE
Cannot register DOI metadata

### ISSUE THREAD

**Issue by ollehints** [geocollections/sarv-edit#556]
On DOI metadata registration/update "Access is denied" error is returned. 
For instance, try to register https://edit2.geocollections.info/doi/502

**Comment by enmust** [comment]
This is a weird error and I still don't know exactly what is causing it. 

MDS docs says 403 for register metadata is:
![image](https://user-images.githubusercontent.com/14908993/95732206-2ffb8e00-0c89-11eb-9008-13203caf773f.png)
but we get 'acces is denied'

But everything seems to work with existing records, I tried to update metadata and etc. + test environment worked also. 
Need to test if this problem is only happening with new records.
